version: "3.7"

services:

  server:
    command: flask run
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - flask.env
    ports:
      - "5000:5000"
    volumes:
      - .:/var/server
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    volumes:
      - /var/lib/postgresql/data

networks:
  default:
    external:
      name: workssingleview
