"""empty message

Revision ID: 356455abb4a6
Revises: 17d2ede29cab
Create Date: 2020-06-05 08:05:47.761576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356455abb4a6'
down_revision = '17d2ede29cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_public_work_iswc'), 'work', ['iswc'], unique=False, schema='public')
    op.drop_index('ix_work_iswc', table_name='work')
    op.create_index(op.f('ix_public_work_provider_provider_id'), 'work_provider', ['provider_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_work_provider_work_id'), 'work_provider', ['work_id'], unique=False, schema='public')
    op.drop_index('ix_work_provider_provider_id', table_name='work_provider')
    op.drop_index('ix_work_provider_work_id', table_name='work_provider')
    op.drop_constraint('work_provider_work_id_fkey', 'work_provider', type_='foreignkey')
    op.drop_constraint('work_provider_provider_id_fkey', 'work_provider', type_='foreignkey')
    op.create_foreign_key(None, 'work_provider', 'work', ['work_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'work_provider', 'provider', ['provider_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_provider', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'work_provider', schema='public', type_='foreignkey')
    op.create_foreign_key('work_provider_provider_id_fkey', 'work_provider', 'provider', ['provider_id'], ['id'])
    op.create_foreign_key('work_provider_work_id_fkey', 'work_provider', 'work', ['work_id'], ['id'])
    op.create_index('ix_work_provider_work_id', 'work_provider', ['work_id'], unique=False)
    op.create_index('ix_work_provider_provider_id', 'work_provider', ['provider_id'], unique=False)
    op.drop_index(op.f('ix_public_work_provider_work_id'), table_name='work_provider', schema='public')
    op.drop_index(op.f('ix_public_work_provider_provider_id'), table_name='work_provider', schema='public')
    op.create_index('ix_work_iswc', 'work', ['iswc'], unique=False)
    op.drop_index(op.f('ix_public_work_iswc'), table_name='work', schema='public')
    # ### end Alembic commands ###
